#!/usr/bin/env bash
# diplay "Best "school" and "hi" at 9 nth position

name="Best School"

counter=1

while [ $counter -le 10 ]
do
	if [ $counter -eq 9 ]; then
		echo "Hi"
	else
		echo "$name"
	fi
	((counter++))
done
