#!/usr/bin/env bash
# display "bad luck" for 4th loop, and "good luck" for 8th

name="Best School"

counter=1

while [ $counter -le 10 ]
do
	if [ $counter -eq 4 ]; then
		echo "bad luck"
	elif [ $counter -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((counter++))
done
